### ISSUE TITLE
GPL

### ISSUE THREAD

**Issue by kernel-panic69** [i3roly/glibc_ddwrt#1]
Please publish your entire source code repository required for compiling this version of DD-WRT in accordance with the GPL, version 2 under which the Official DD-WRT firmware is published.  Thank you.

**Comment by i3roly** [comment]
in short: you are a loser.

secondly: your 'boss' hasn't adhered with GPL policy and i can prove it. until a lawyer asks me to do so: FUCK OFF.

do you understand? i don't like you. and i've said many times the source for dd-wrt is unchanged. i'm not giving you my build files and the build files aren't "source code". do you understand?

i posted my reasoning already. you obviously have an issue with it, and rolling an account to comment on my github is proof that my DD_WRT is simply BUILT BETTER than your boss'.

get a life. or an education. you have neither right now.
