### ISSUE TITLE
GUI Webpage 404

### ISSUE THREAD

**Issue by nikolatesluh** [i3roly/glibc_ddwrt#16]
I was running on v50486 and decided to update. I tried to open the GUI and was greeted with this page, i figured it needed to be updated with the SSH method like you had asked and i did the same, Even after the upgrade via ssh, this stays the same, then I tried to load the factory-to-ddwrt through emergency mode and the webpage still gives the error screen and it is not reset. now i will try to reset the nvram and post an update. 

![image](https://user-images.githubusercontent.com/8076008/200572990-0fdb5319-3579-49da-bc06-8fde6423766d.png)

**Comment by nikolatesluh** [comment]
update, nvram reset worked, but for some reason, i am unable to connect to PPPoE, the connection in itself is fine, even when the gui wasnt working, after updating to v50813 internet was working.

**Comment by nikolatesluh** [comment]
Went back to v50486 PPPoE working

**Comment by i3roly** [comment]
what firmawre version did you try? i am using 50806, which is really not that different from what i posted, and everything is fine.

you need to be more descriptive.

**Comment by i3roly** [comment]
i'm going to update to 50813 right now and see what happens. 

 i cna't see how 50806 and 50813 would differ enough to cause that issue

**Comment by i3roly** [comment]
looks fine to me.

closing ntil you can provide real evidence. i have no idea how you got that screen.
![Screenshot 2022-11-08 at 8 23 09 AM](https://user-images.githubusercontent.com/36090395/200605272-ef7a3ba8-50fb-4227-9c40-4b53c9139eed.png)
