### ISSUE TITLE
Wifi physical interfaces disappears in latest build

### ISSUE THREAD

**Issue by nikolatesluh** [i3roly/glibc_ddwrt#19]
I flashed the latest build v53391 and my wifi physical interfaces disappeared. LAN was working fine. 

Flashed to v53142 and the interfaces were restored with the previous used configuration. 

Edit1: Router: DIR-882

**Comment by i3roly** [comment]
are you saying there is no wifi at all?

that's weird.

there shouldn't be any problem i didn't change anything
________________________________
From: Tesluh ***@***.***>
Sent: August 23, 2023 9:13 AM
To: i3roly/glibc_ddwrt ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [i3roly/glibc_ddwrt] Wifi physical interfaces disappears in latest build (Issue #19)


I flashed the latest build v53391 and my wifi physical interfaces disappeared. LAN was working fine.

Flashed to v53142 and the interfaces were restored with the previous used configuration.

**Comment by i3roly** [comment]
new build is up. try it out and report back please.

**Comment by nikolatesluh** [comment]
> i looked again, and i think i found the issue. what router? 882 or 878? it's very possible that what i screwed up was something simple (i commented out some make rules that i didn't comment back in). wondering if your webgui even said 53391? probably not?> i'm going to post 53418 right away so let me know. thanks

Yes, it my router is 882 and i downloaded  the right version as well. 
i didnt pay attention to be very honest if it said the version, but the page title did say the version,  however i am not sure what version it said.

Flashed the new build, it is working fine, Thank  You!
