### ISSUE TITLE
SAMBA USB File sharing not working in 47458M D-Link 266O

### ISSUE THREAD

**Issue by Nikhchan** [i3roly/glibc_ddwrt#5]
Got this running after a bit of trial and error.

But I can't get USB NAS SAMBA file sharing to work. The 4 tb USB disk is mounted fine. But under NAS tab, the file sharing block is empty. No options appear there.

I was able to get MiniDLNA to work, so it's able to access my USB disk and can play media from it as well. 

Here are the options I've set.

https://i.postimg.cc/tTL5zWbr/IMG-20210916-031623.jpg
https://i.postimg.cc/HxJz53qc/IMG-20210916-031646.jpg

Its the same in 47458M and the previous version before this. 47451. 

Any help would be appreciated as it worked just fine in stock D-Link firmware.

Will test other capabilities.

**Comment by i3roly** [comment]
will be fixed in the next build i'll be uploading in less than ten minutes.

thanks for catching this very big omission.

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/ZwXlTqjyf54/0.jpg)](https://www.youtube.com/watch?v=ZwXlTqjyf54)

close the ticket if it's fixed at that point.

**Comment by Nikhchan** [comment]
> will be fixed in the next build i'll be uploading in less than ten minutes.
> 
> thanks for catching this very big omission.
> 
> close the ticket if it's fixed at that point.
> 
> [![IMAGE ALT TEXT HERE](https://camo.githubusercontent.com/8be59aa62ba419c2ac812e36f9bc8d010d2c37dd2a359dc1f60681134010bf1b/68747470733a2f2f696d672e796f75747562652e636f6d2f76692f5a77586c54716a796635342f302e6a7067)](https://www.youtube.com/watch?v=ZwXlTqjyf54)

I did

**Comment by Nikhchan** [comment]
> will be fixed in the next build i'll be uploading in less than ten minutes.
> 
> thanks for catching this very big omission.
> 
> close the ticket if it's fixed at that point.
> 
> [![IMAGE ALT TEXT HERE](https://camo.githubusercontent.com/8be59aa62ba419c2ac812e36f9bc8d010d2c37dd2a359dc1f60681134010bf1b/68747470733a2f2f696d672e796f75747562652e636f6d2f76692f5a77586c54716a796635342f302e6a7067)](https://www.youtube.com/watch?v=ZwXlTqjyf54)

Hi I did install this new version.

The options do indeed show up now. 

But the path isn't complete. 

It's showing /dev & /mnt options only in shares. 
I thought I have to add /sda1 in subdir but that's not how I remember doing it and it didn't work. 

The same mount points /dev & /mnt are there in DLNA.

https://i.postimg.cc/W4yvbXRY/IMG-20210916-173521.jpg
https://i.postimg.cc/26Bfqhrk/IMG-20210916-173543.jpg

**Comment by i3roly** [comment]
listen, i've tolerated you pretty well considering you didn't even know how to flash the firmware.

i remember you messaging me on the dlink forum as if i'm one of your respected friends who does tech support for a living, i don't.

the fact you continue your bold conduct without being certain of the accuracy is annoying. being right once, in spite of not knowing how to flash the firmware, is not permission to continue your conduct.

as my pictures show, it's perfectly fine. you obviously don't fully know what you're doing
![Screenshot 2021-09-16 at 8 23 58 AM](https://user-images.githubusercontent.com/36090395/133630193-f8585963-732a-4971-9ebc-56d07e2f4ce5.png)

**Comment by Nikhchan** [comment]
> listen, i've tolerated you pretty well considering you didn't even know how to flash the firmware.
> 
> i remember you messaging me on the dlink forum as if i'm one of your respected friends who does tech support for a living, i don't.
> 
> the fact you continue your bold conduct without being certain of the accuracy is annoying. being right once, in spite of not knowing how to flash the firmware, is not permission to continue your conduct.
> 
> as my pictures show, it's perfectly fine. you obviously don't fully know what you're doing
> ![Screenshot 2021-09-16 at 8 23 58 AM](https://user-images.githubusercontent.com/36090395/133630193-f8585963-732a-4971-9ebc-56d07e2f4ce5.png)

Wow...talk about being  rude. I only tried your firmware to try and help you others and provide feedback on it with a different model. The HDD issue was fixed by repairing the drive with windows. 

It seems you don't care much for this project. 

So at least provide me the passage out. It's not letting me flash my stock firmware via recovery after flashing this one. "upgrade failed!" Does it change anything in the firmware? Because DD-WRT ids my router as DIR 882 A1.

**Comment by nikolatesluh** [comment]
> 
> 
> > listen, i've tolerated you pretty well considering you didn't even know how to flash the firmware.
> > i remember you messaging me on the dlink forum as if i'm one of your respected friends who does tech support for a living, i don't.
> > the fact you continue your bold conduct without being certain of the accuracy is annoying. being right once, in spite of not knowing how to flash the firmware, is not permission to continue your conduct.
> > as my pictures show, it's perfectly fine. you obviously don't fully know what you're doing
> > ![Screenshot 2021-09-16 at 8 23 58 AM](https://user-images.githubusercontent.com/36090395/133630193-f8585963-732a-4971-9ebc-56d07e2f4ce5.png)
> 
> Wow...talk about being rude. I only tried your firmware to try and help you others and provide feedback on it with a different model. The HDD issue was fixed by repairing the drive with windows.
> 
> It seems you don't care much for this project.
> 
> So at least provide me the passage out. It's not letting me flash my stock firmware via recovery after flashing this one. "upgrade failed!" Does it change anything in the firmware? Because DD-WRT ids my router as DIR 882 A1.

As you wanted a way out, try following the guide [here](http://forums.dlink.com/index.php?topic=75536.0) using an older f/w. Should work out for you.

**Comment by i3roly** [comment]
@Nikhchan i assume the 2640 is working fine yes?
